### ISSUE TITLE
Need to investigate `mobile_subscriptions` table and THE QUERY, to ensure run_id accuracy.

### ISSUE THREAD

**Issue by sheyd** [DoSomething/quasar#125]
Per Slack conversation with @nmccormick619:

```
realized that not all mobile subscriptions in the MML table associate with a run_nid
[10:55] 

so for example - love letters 2016 - if you try to look at signups to that campaign via the mml table by run nid you get like 1000

[10:55] 
if you search by mc campaign id you get the correct number - 14000
```
and

```
select distinct ms_phone_number
from mobile_master_lookup
where ms_campaign_id=140641

[11:06] 
or

select distinct ms_phone_number
from mobile_master_lookup
where ms_run_nid=XXX
```

TLDR:

Need to investigate `mobile_subscriptions` table and THE QUERY, to ensure run_id accuracy.

**Comment by Bladt** [comment]
Testing Mobile commons campaign id: 140641 (LoveLetters2016 - Sign Up)
Total sign up counts
GUI: 14,630 (distinct, includes subscribed and unsubscribed) 
MML: 14,630 (distinct), 15,136 (all) --- based on mobile campaign id
MS: 14,630 (distinct), 15,136 (all) --- based on mobile campaign id
The Query: 1,552 (run_nid = 6521)

**Comment by Bladt** [comment]
Ok --- I think this is the issue. Looking at the MML table:

When the `mc_opt_in_path_id` field is null, the `mc_run_id` field is also null, even when the `ms_campaign_id` field has an id that relates to a run_nid. This prevents these sign ups from being counted in the analytics layer (the query, or now Looker etc) because we need to be able to group by run_nid, which in this case is the 'mc_run_id' column in the MML table. 

Of the 15,136 entries with 140641 as the `ms_campaign_id`, only 1,552 have a `mc_run_id'

What is preventing the 'mc_run_id' field from being populated?

**Comment by namimody** [comment]
@sheyd @Bladt could you share the status on this?

**Comment by namimody** [comment]
@sheyd @nmccormick619 could you add a comment with the latest status on this? thanks!

**Comment by sheyd** [comment]
@Bladt @nmccormick619 I think we addressed this via `master_mobile_lookup_lite`, right?

**Comment by Bladt** [comment]
@sheyd @namimody Correct, MML Lite solved this.
