### ISSUE TITLE
Context Clues Heat Map 

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#187]
_TASK_
------------------
#### Request
https://trello.com/c/DtTciezi/978-context-clues-looker-request

**Comment by jessleenyc** [comment]
Lock view area so it's not requeried every time the user moves the map.

**Comment by nmccormick619** [comment]
Currently working on this. The mapping solutions in Looker aren't super clean so I will chat with the Looker team to see if there is anything I'm missing in terms of mapping!

**Comment by nmccormick619** [comment]
So - chatted with the Looker team. There is a whole custom mapping feature that I don't think we're actually ready to explore...documentation here: https://discourse.looker.com/t/using-map-layers-in-static-region-maps-3-42-and-interactive-maps-3-50/2303/4

@Bladt, if okay with you, I'd like to table this conversation with BizDev. (1) Is purely because it seems like an advanced feature and (2) Is because the visualization is driven by data points that we may not actually have (eg - there are no dots showing in the Dakotas because we didn't have signups in those areas), and so I'm not sure creating anything visually enticing is actually going to fulfill the team's needs for sponsors.

Let me know your thoughts and we can revisit in the future.

**Comment by nmccormick619** [comment]
Per conversation - may use codev session to revisit mapping in the future. Not a priority right now.
