### ISSUE TITLE
Niche Dashboard

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#191]
_TASK_
-------------------
#### Request
Build a Niche dashboard that has combined info from KPI & Repeat Verified dash.

**Comment by Bladt** [comment]
@jessleenyc (and @nmccormick619 if you are interested), here is the v1 of the niche dash: https://data.dosomething.org/dashboards/10. 

It is ready for QA. My first instinct was to try to create (Look-for-Look) the repeat verified dash, but with the source filter inverted. This tact resulted in a less-than-helpful set of data. What is shared here is my first attempt to provide the right Looks to assess Niche performance and provide top level stats. As much, I would love to involve James et al in the QA process to see if my hunches on what is insightful were right.

**Comment by jessleenyc** [comment]
Add: Overall SMS RB Rate - Are we able to show % of RBs w/ SMS as a source?

**Niche Users Added By Month** - Any idea why this number is so low in July?

**Niche Members w/ 1+ Logins By Join Month** - This is 1+ logins from when they joined, not also within the month they joined? i.e. accounts for members who joined in june but then logged in a second time in august?

**Niche Web Sign Ups by No. Of Days Since Joining DS:** So to make sure I'm understanding this correctly, in July there were 2,955 members who signed up for a campaign on DS that were first seen on Niche 90+ days prior that sign up?

**Members With 1+ Reportbacks In First 60m** - Update m to minutes

**Comment by jessleenyc** [comment]
I'll set up a time to review this with James this week!

**Comment by Bladt** [comment]
@jessleenyc 

_Add: Overall SMS RB Rate - Are we able to show % of RBs w/ SMS as a source?_

Due to schema limitations, we do not have user source (and most other user level pieces of data) joined to  mobile sign-ups. Meaning that we can't calculate sms rb rate specifically for niche members, b/c we can't differentiate sms sign ups by source. 

We could. What questions would this help to answer about Niche performance/strategy?

_Niche Users Added By Month - Any idea why this number is so low in July?_

We suspending the budget in July

_Niche Members w/ 1+ Logins By Join Month - This is 1+ logins from when they joined, not also within the month they joined? i.e. accounts for members who joined in june but then logged in a second time in august?_

Correct. E.g. 5.8% of niche members that joined in April-2015 have ever logged into their account. 

_Niche Web Sign Ups by No. Of Days Since Joining DS: So to make sure I'm understanding this correctly, in July there were 2,955 members who signed up for a campaign on DS that were first seen on Niche 90+ days prior that sign up?_

Correct. I find this Look helpful in sussing up re-engagement of Niche members. That 90+ D cohort should increase every month if we are doing our jobs right. 

_Members With 1+ Reportbacks In First 60m - Update m to minutes_

Done. 

I also added last 7 day changes to the Overall Stats at the top of the Dashboard.

**Comment by jessleenyc** [comment]
@Bladt 

**Add: Overall SMS RB Rate - Are we able to show % of RBs w/ SMS as a source?**

_Due to schema limitations, we do not have user source (and most other user level pieces of data) joined to mobile sign-ups. Meaning that we can't calculate sms rb rate specifically for niche members, b/c we can't differentiate sms sign ups by source.

We could. What questions would this help to answer about Niche performance/strategy?_

Since niche users who provide their phone numbers also get texts from DS, I think there's value in seeing what  % are choosing to engage vis SMS instead of the web. Since the overall rb rates for niche signups are low, it would be interesting if we're seeing more of the rbs coming from sms.

**Comment by jessleenyc** [comment]
@bladt Notes from our meeting w/ James:
- Update: web rb rate in last 30 days delta to show the actual reportback rate in last 30 days
- Add: % of members that accessed the site 1 + times within last 7 days of account creation. We know these members will get pulled out of the group of they re-access 7+ days later.

**Comment by Bladt** [comment]
@jessleenyc added the two outstanding items. LMK if the placement of the accessed 1+...look makes sense

**Comment by jessleenyc** [comment]
@Bladt per our convo, let's add a graph that shows most popular campaigns niche users sign up for in current month!

**Comment by jessleenyc** [comment]
WHOO!
