### ISSUE TITLE
Mobile Commons Job Fail: Run backfill and investigate root cause

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#239]
_BUG_
-------------------
#### Current Behavior
Mobile commons job failed - science sleuth numbers out of date. Need to run a 36 hour backfill.

**Comment by jessleenyc** [comment]
Ran backfill but jobs still failed over the weekend. Re-running and @sheyd investigating root cause.

**Comment by sheyd** [comment]
Looks like more intermediary network failures. It seems like the networking routes to MC occasionally have issues (from multiple providers we've seen at this point). 

I'm testing using `retries` and `delay_between_requests` arguments in subscriber script to see if that will fix the issue (somewhat by rote force/hackery).

**Comment by sheyd** [comment]
Waiting on test back-fill to run.

**Comment by sheyd** [comment]
Round-up of testing. After adjusting the retry values around a bit, and changing the URI request (from ds.mc.com back to secure.mc.com), we had a successful mobile campaign backfill (still need to run user backfill). 

The bad part is I only have one successful run as base evidence to show that this works. I'm going to go ahead and update the code in our ETL scripts to use both `secure.mc.com` instead of `ds`, as well as add the same retry/backoff logic that combo that seems to have worked for Mobile Campaigns backfill. For reference, the combo I used is 6 retries with 10 minute backoff period.

**Comment by sheyd** [comment]
The logic in code looks something like this:

```
req = requests.Session()
retries = Retry(total=6, backoff_factor=600)
req.mount('https://', HTTPAdapter(max_retries=retries))
```

The scripts also need additional import statements for retry and alternate adapters:

**Comment by sheyd** [comment]
Scripts updated and are currently in testing. Users backfill for 72 hours ran fine. Mobile Subscriptions for campaign checking running as well, will confirm if/when it completes.

**Comment by sheyd** [comment]
All MC scripts seem to be running a lot better based on past 2 days of running jobs with retries built-in.

**Comment by sheyd** [comment]
Closing unless we have to adjust things further.
