### ISSUE TITLE
Replicate Phoenix DB to Quasar (real time)

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/quasar#257]

**Comment by sheyd** [comment]
Initial transfer complete. Monitoring on-going replication, since there are some insert/error logs that are cropping up. Seeing if they're relevant or not.

**Comment by sheyd** [comment]
With AWS support since on-going replication was stuck on a record. Following their advice and modified some settings. Should hear back more in the next few hours.

**Comment by sheyd** [comment]
Some records aren't updating properly, although there are less errors now. AWS support is going to call me to do a screenshare and troubleshoot further.

**Comment by sheyd** [comment]
So it looks like the replication instance size (the server that actually does the DB replication) was massively overloaded. I'm upgrading the instance size and will re-initialize the DB sync to see how things go.

**Comment by sheyd** [comment]
Just in case, I'm exploring other options for MySQL replication into AWS on a real-time basis.

**Comment by sheyd** [comment]
So far the best options appear to be Embulk or Tungsten Replicator. I'm slightly biased towards Tungsten since I've actually used it before.

**Comment by sheyd** [comment]
Unfortunately, the real-time replication in DMS has a schema issue with deleting record from the `field_data_field_birthdate` field after initial import (which works successfully). The import takes ~30 minutes, so instead of introducing external dependencies and setup of Tungsten or Embulk, I'm going to write a Jenkins job that automates the following steps:

* Runs full-sync replication from Phoenix RDS to Redshift with schema name `dosomething_latest_sync`
* Monitor DMS job for completion.
* Rename Redshift `dosomething` schema to `dosomething_old`
* Rename Redshift `dosomething_latest_sync` schema to `dosomething`
* Drop `dosomething_old` schema.

Current POC cron will be at 2 hours.

**Comment by sheyd** [comment]
Process tested and put into Jenkins with Slack notifications.
