### ISSUE TITLE
MongoDB Northstar Queries are Slow Again, Investigate Why

### ISSUE THREAD

**Issue by sheyd** [DoSomething/quasar#330]
_BUG_
-------------------
#### Current Behavior
Mongo queries to Northstar to user endpoint are taking up to 3 seconds again regularly. Not sure why. :(

#### Desired Behavior
Mongo queries to be back down to 100's of ms range.

#### Steps to Replicate
Watch backfill and real-time data queries.

#### Why This Matters
Don't want to kill Northstar or Mongo DB. Faster backfills.

**Comment by DFurnes** [comment]
This seems to be a [known issue with `skip` queries](https://docs.mongodb.com/manual/reference/method/cursor.skip/), which is how the `jenssegers/laravel-mongodb` package handles cursor pagination. It seems like the suggested fix is to  paginate based on ranges (like `?after=xxx` rather than `?page=#`), which is frustrating but not a totally crazy thing to try to implement.

**Comment by sheyd** [comment]
@DFurnes Thanks for looking at this. Thankfully most of our full backlog fills are done, so this can wait a few sprints.
