### ISSUE TITLE
Users registration source mislabeled as SMS 

### ISSUE THREAD

**Issue by jamjensen** [DoSomething/quasar#356]
_BUG_
-------------------
#### Current Behavior
There are ~20k accounts created since May 12 whose registration source is incorrectly labeled as SMS. As Furnes pointed out, if we are syncing MoCo profiles and found someone who had texted in a keyword before they registered on www.dosomething.org - their registration source would be backdated as SMS. 

There are 14k accounts with niche as registration source and 5,700 accounts with phoenix-oauth as registration source in the `field_data_field_registration_source` table -- all created since May 12 -- that have SMS as registration source in the quasar `users` table. 

![image](https://cloud.githubusercontent.com/assets/19572934/26606078/89a4fc48-455e-11e7-8bd2-12c31f376b69.png)

#### Desired Behavior
Registration source should be the same in both the quasar `users` table and the `field_data_field_registration_source` table. 

#### Steps to Replicate
??? 

#### Why This Matters
Because we're incorrectly labeling registration source.

**Comment by jamjensen** [comment]
Interested in why their are so many accounts with registration source as phoenix-oauth backdated. If your first interaction with a DS campaign after creating an account through oauth is over SMS can your registration source be backdated?

**Comment by DFurnes** [comment]
Yeah, this is interesting. We only allow Northstar to change user's `source` if an earlier `created_at` date is provided in the same request – so if I have an account registered on Phoenix on Tuesday, and [northstar-mobilecommonsd](https://github.com/DoSomething/northstar-mobilecommonsd) later sends a request saying it was actually first seen on SMS on Monday, that'd be the new `source` value. (Ideally!)

The `user_registration_source` field in Drupal does not get backdated (it will only include whatever Northstar values existed when the account was first created), so that explains why it still says `niche`. That said, it's pretty weird that this is getting backdated at all!

I think the specific problem here is that we'll consider a newly provided source with the same `created_at` to be a valid update (so "earlier than or equal to" rather than exclusively "earlier than"). 

For example, [this user](https://aurora.dosomething.org/users/591f387ea0bfad323b208a1c) and their [MobileCommons profile](https://secure.mcommons.com/profiles/228504233) have the exact same "created at" timestamp. Our MobileCommons syncer pulls in profiles on a 5-10 minute delay so it would have overwritten any Niche profiles that have phone numbers.

I'll make a PR to Northstar to change that logic so it doesn't happen to future imports, and then we can make a quick script to fix these users who were affected by this bug.

**Comment by DFurnes** [comment]
Another thing that's worth considering is if we're really doing any meaningful backfills anymore, and if not perhaps just removing that logic?

**Comment by jamjensen** [comment]
*Update as of 6/6* 
- DF to put in a quick fix so that we don't continue to override registration source for niche users 
- Discuss backfilling registration source for niche users whose source was updated to be 'sms' at next sprint planning.
