### ISSUE TITLE
Resolve Active Member Count Discrepancy (Mobile Commons)

### ISSUE THREAD

**Issue by jamjensen** [DoSomething/quasar#383]
_BUG_
-------------------
#### Current Behavior
- Mobile Commons UI displays 3,549,351 active members and querying `users` table only displays 3,531,909. 

#### Why This Matters
-  We're potentially undercounting the total number of members on our Mobile Commons list.

**Comment by jamjensen** [comment]
@sheyd can you please: 

- [ ] query Northstar mongo db to check if the total number of active mobile users is same as number in MoCo UI. 
- [ ] download csv of all members with unsubscribed = false from customer.io and put this info into a table so that I can isolate subscribed members in `users` that are missing from our c.io list

**Comment by jamjensen** [comment]
@DFurnes I'm seeing a difference between the number of records whose Mobile Commons status = 'active' and the number of active subscribers that are listed in the Mobile Commons UI. Here's the breakdown of active MoCo subscribers: 
- number from northstar db: 3,535,620
- number from `quasar.users`: 3,535,634 (taken minutes after Sena queried NS db)
- number from MoCo UI: 3,556,014

As you can see, the number in `quasar.users` mirrors what we have in the NS db. So the discrepancy is between Mobile Commons and Northstar. Any idea why Northstar would have ~20k fewer active subscribers than Mobile Commons? Can we track down and ingest active Mobile Commons subscribers missing from Northstar?

**Comment by sheyd** [comment]
@jamjensen Okay, `users_c_io_count`  and `c_io_export_071117` snapshot tables are ready for you to rock and roll with!

**Comment by jamjensen** [comment]
@DFurnes Wanted to follow up on my comment above ^ -- 

Would you be able to investigate why there is a difference in total number of active mobile subscribers between MoCo UI and what we've ingested into Northstar?

**Comment by DFurnes** [comment]
I'm not sure, but I can definitely try to do some investigation. 🕵️

**Comment by DFurnes** [comment]
I pulled the logs and don't see anything unexpected – the full backfill seems to have run for records from 4/01/2009 – 5/17/2017 with no notable gaps, and we've continued pulling records every 5 minutes since then.

There are 104 users that have hit validation errors while syncing in their records but that's not nearly enough to account for the gap you're seeing: looking at a few of those records, it seems like they're all fake mobile numbers ([11111111111](https://secure.mcommons.com/profiles/149172853), [10000000000](https://secure.mcommons.com/profiles/51267181), [33333333333](https://secure.mcommons.com/profiles/172718643)). MobileCommons stores a profile with a "Not a Mobile Number" flag, we reject it altogether.
